"""empty message

Revision ID: 55e3663f1f51
Revises: f1ae5c430eab
Create Date: 2022-06-08 22:54:39.306476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e3663f1f51'
down_revision = 'f1ae5c430eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_description', sa.String(length=210), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'seeking_description')
    # ### end Alembic commands ###
